CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "Category" (
    "CategoryId" integer GENERATED BY DEFAULT AS IDENTITY,
    "CategoryName" text NOT NULL,
    "ImageUrl" text,
    CONSTRAINT "PK_Category" PRIMARY KEY ("CategoryId")
);

CREATE TABLE "emailOTPs" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Email" text NOT NULL,
    "OTP" text NOT NULL,
    "ExpiryTime" timestamp with time zone NOT NULL,
    "IsVerified" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_emailOTPs" PRIMARY KEY ("Id")
);

CREATE TABLE "Role" (
    "RoleId" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    CONSTRAINT "PK_Role" PRIMARY KEY ("RoleId")
);

CREATE TABLE "Users" (
    "UserId" integer GENERATED BY DEFAULT AS IDENTITY,
    "userName" text NOT NULL,
    "userEmail" text NOT NULL,
    "userPassword" text NOT NULL,
    "RoleId" integer NOT NULL,
    CONSTRAINT "PK_Users" PRIMARY KEY ("UserId"),
    CONSTRAINT "FK_Users_Role_RoleId" FOREIGN KEY ("RoleId") REFERENCES "Role" ("RoleId") ON DELETE CASCADE
);

CREATE TABLE "Cart" (
    "CartId" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    CONSTRAINT "PK_Cart" PRIMARY KEY ("CartId"),
    CONSTRAINT "FK_Cart_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("UserId") ON DELETE CASCADE
);

CREATE TABLE consumers (
    "ConsumerId" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "FirstName" text NOT NULL,
    "LastName" text NOT NULL,
    "Phone" text NOT NULL,
    "Gender" text NOT NULL,
    "Date_of_Birth" timestamp with time zone NOT NULL,
    profileimage text NOT NULL,
    CONSTRAINT "PK_consumers" PRIMARY KEY ("ConsumerId"),
    CONSTRAINT "FK_consumers_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("UserId") ON DELETE CASCADE
);

CREATE TABLE "Retailers" (
    "RetailerId" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "ShopName" text NOT NULL,
    "ShopDescription" text NOT NULL,
    "Address" text NOT NULL,
    "City" text NOT NULL,
    "State" text NOT NULL,
    "Pincode" text NOT NULL,
    "ContactNumber" text NOT NULL,
    "AlternateNumber" text,
    "GSTNumber" character varying(15) NOT NULL,
    "PANNumber" text NOT NULL,
    "BankAccountNumber" text NOT NULL,
    "IFSCCode" text NOT NULL,
    "AccountHolderName" text NOT NULL,
    "LogoUrl" text,
    "BannerUrl" text,
    "IsVerified" boolean NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Retailers" PRIMARY KEY ("RetailerId"),
    CONSTRAINT "FK_Retailers_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("UserId") ON DELETE CASCADE
);

CREATE TABLE "UserAddress" (
    "AddressId" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "FullName" text NOT NULL,
    "Phone" text NOT NULL,
    "AddressLine" text NOT NULL,
    "City" text NOT NULL,
    "State" text NOT NULL,
    "Pincode" text NOT NULL,
    "Latitude" double precision,
    "Longitude" double precision,
    "IsDefault" boolean NOT NULL,
    CONSTRAINT "PK_UserAddress" PRIMARY KEY ("AddressId"),
    CONSTRAINT "FK_UserAddress_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("UserId") ON DELETE CASCADE
);

CREATE TABLE "Products" (
    "productId" integer GENERATED BY DEFAULT AS IDENTITY,
    "productName" text NOT NULL,
    "Description" text NOT NULL,
    "productAdded" timestamp with time zone NOT NULL,
    "CategoryId" integer NOT NULL,
    "productPrice" double precision NOT NULL,
    "RetailerId" integer NOT NULL,
    stock integer NOT NULL,
    "UsersUserId" integer,
    CONSTRAINT "PK_Products" PRIMARY KEY ("productId"),
    CONSTRAINT "FK_Products_Category_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES "Category" ("CategoryId") ON DELETE CASCADE,
    CONSTRAINT "FK_Products_Retailers_RetailerId" FOREIGN KEY ("RetailerId") REFERENCES "Retailers" ("RetailerId") ON DELETE CASCADE,
    CONSTRAINT "FK_Products_Users_UsersUserId" FOREIGN KEY ("UsersUserId") REFERENCES "Users" ("UserId")
);

CREATE TABLE orders (
    "OrderId" integer GENERATED BY DEFAULT AS IDENTITY,
    "UsersId" integer NOT NULL,
    "OrderDate" timestamp with time zone NOT NULL,
    "Status" text NOT NULL,
    "AddressId" integer NOT NULL,
    CONSTRAINT "PK_orders" PRIMARY KEY ("OrderId"),
    CONSTRAINT "FK_orders_UserAddress_AddressId" FOREIGN KEY ("AddressId") REFERENCES "UserAddress" ("AddressId") ON DELETE CASCADE,
    CONSTRAINT "FK_orders_Users_UsersId" FOREIGN KEY ("UsersId") REFERENCES "Users" ("UserId") ON DELETE CASCADE
);

CREATE TABLE "cartItems" (
    "CartItemId" integer GENERATED BY DEFAULT AS IDENTITY,
    "CartId" integer NOT NULL,
    "ProductId" integer NOT NULL,
    "Quantity" integer NOT NULL,
    CONSTRAINT "PK_cartItems" PRIMARY KEY ("CartItemId"),
    CONSTRAINT "FK_cartItems_Cart_CartId" FOREIGN KEY ("CartId") REFERENCES "Cart" ("CartId") ON DELETE CASCADE,
    CONSTRAINT "FK_cartItems_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products" ("productId")
);

CREATE TABLE "ProductImages" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ImageUrl" text NOT NULL,
    "ProductId" integer NOT NULL,
    CONSTRAINT "PK_ProductImages" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ProductImages_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products" ("productId") ON DELETE CASCADE
);

CREATE TABLE "WishlistItems" (
    "WishlistItemId" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "ProductId" integer NOT NULL,
    "AddedOn" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_WishlistItems" PRIMARY KEY ("WishlistItemId"),
    CONSTRAINT "FK_WishlistItems_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products" ("productId") ON DELETE CASCADE,
    CONSTRAINT "FK_WishlistItems_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("UserId")
);

CREATE TABLE "orderItems" (
    "OrderItemId" integer GENERATED BY DEFAULT AS IDENTITY,
    "OrderId" integer NOT NULL,
    "ProductId" integer NOT NULL,
    "RetailerId" integer NOT NULL,
    "Quantity" integer NOT NULL,
    "Price" double precision NOT NULL,
    "Status" text NOT NULL,
    CONSTRAINT "PK_orderItems" PRIMARY KEY ("OrderItemId"),
    CONSTRAINT "FK_orderItems_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products" ("productId"),
    CONSTRAINT "FK_orderItems_orders_OrderId" FOREIGN KEY ("OrderId") REFERENCES orders ("OrderId") ON DELETE CASCADE
);

CREATE INDEX "IX_Cart_UserId" ON "Cart" ("UserId");

CREATE INDEX "IX_cartItems_CartId" ON "cartItems" ("CartId");

CREATE INDEX "IX_cartItems_ProductId" ON "cartItems" ("ProductId");

CREATE UNIQUE INDEX "IX_consumers_UserId" ON consumers ("UserId");

CREATE INDEX "IX_orderItems_OrderId" ON "orderItems" ("OrderId");

CREATE INDEX "IX_orderItems_ProductId" ON "orderItems" ("ProductId");

CREATE INDEX "IX_orders_AddressId" ON orders ("AddressId");

CREATE INDEX "IX_orders_UsersId" ON orders ("UsersId");

CREATE INDEX "IX_ProductImages_ProductId" ON "ProductImages" ("ProductId");

CREATE INDEX "IX_Products_CategoryId" ON "Products" ("CategoryId");

CREATE INDEX "IX_Products_RetailerId" ON "Products" ("RetailerId");

CREATE INDEX "IX_Products_UsersUserId" ON "Products" ("UsersUserId");

CREATE INDEX "IX_Retailers_UserId" ON "Retailers" ("UserId");

CREATE INDEX "IX_UserAddress_UserId" ON "UserAddress" ("UserId");

CREATE INDEX "IX_Users_RoleId" ON "Users" ("RoleId");

CREATE INDEX "IX_WishlistItems_ProductId" ON "WishlistItems" ("ProductId");

CREATE INDEX "IX_WishlistItems_UserId" ON "WishlistItems" ("UserId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260609062514_database', '10.0.9');

COMMIT;

START TRANSACTION;
ALTER TABLE "Products" ADD "SubCategoryId" integer NOT NULL DEFAULT 0;

CREATE TABLE "SubCategory" (
    "SubCategoryId" integer GENERATED BY DEFAULT AS IDENTITY,
    "SubCategoryName" text NOT NULL,
    "CategoryId" integer NOT NULL,
    CONSTRAINT "PK_SubCategory" PRIMARY KEY ("SubCategoryId"),
    CONSTRAINT "FK_SubCategory_Category_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES "Category" ("CategoryId") ON DELETE CASCADE
);

CREATE INDEX "IX_Products_SubCategoryId" ON "Products" ("SubCategoryId");

CREATE INDEX "IX_SubCategory_CategoryId" ON "SubCategory" ("CategoryId");

ALTER TABLE "Products" ADD CONSTRAINT "FK_Products_SubCategory_SubCategoryId" FOREIGN KEY ("SubCategoryId") REFERENCES "SubCategory" ("SubCategoryId") ON DELETE CASCADE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260609071309_SUBCATEGORY', '10.0.9');

COMMIT;

START TRANSACTION;
CREATE TABLE "Notifications" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ConsumerId" integer,
    "RetailerId" integer,
    "Type" text NOT NULL,
    "Title" text NOT NULL,
    "Message" text NOT NULL,
    "RelatedOrderId" integer,
    "RelatedProductId" integer,
    "IsRead" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Notifications" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Notifications_Retailers_RetailerId" FOREIGN KEY ("RetailerId") REFERENCES "Retailers" ("RetailerId"),
    CONSTRAINT "FK_Notifications_consumers_ConsumerId" FOREIGN KEY ("ConsumerId") REFERENCES consumers ("ConsumerId")
);

CREATE INDEX "IX_Notifications_ConsumerId" ON "Notifications" ("ConsumerId");

CREATE INDEX "IX_Notifications_RetailerId" ON "Notifications" ("RetailerId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260628084751_Notification', '10.0.9');

COMMIT;

START TRANSACTION;
CREATE TABLE "Reviews" (
    "ReviewId" integer GENERATED BY DEFAULT AS IDENTITY,
    "ProductId" integer NOT NULL,
    "UserId" integer NOT NULL,
    "Rating" integer NOT NULL,
    "Comment" text NOT NULL,
    "IsVerifiedPurchase" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Reviews" PRIMARY KEY ("ReviewId"),
    CONSTRAINT "FK_Reviews_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products" ("productId") ON DELETE CASCADE,
    CONSTRAINT "FK_Reviews_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("UserId") ON DELETE CASCADE
);

CREATE INDEX "IX_Reviews_ProductId" ON "Reviews" ("ProductId");

CREATE INDEX "IX_Reviews_UserId" ON "Reviews" ("UserId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260705182225_review', '10.0.9');

COMMIT;

START TRANSACTION;
CREATE TABLE "ReviewHelpful" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ReviewId" integer NOT NULL,
    "UserId" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_ReviewHelpful" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ReviewHelpful_Reviews_ReviewId" FOREIGN KEY ("ReviewId") REFERENCES "Reviews" ("ReviewId") ON DELETE CASCADE,
    CONSTRAINT "FK_ReviewHelpful_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("UserId") ON DELETE CASCADE
);

CREATE TABLE "ReviewReplies" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ReviewId" integer NOT NULL,
    "RetailerId" integer NOT NULL,
    "Message" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_ReviewReplies" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ReviewReplies_Retailers_RetailerId" FOREIGN KEY ("RetailerId") REFERENCES "Retailers" ("RetailerId") ON DELETE CASCADE,
    CONSTRAINT "FK_ReviewReplies_Reviews_ReviewId" FOREIGN KEY ("ReviewId") REFERENCES "Reviews" ("ReviewId") ON DELETE CASCADE
);

CREATE INDEX "IX_ReviewHelpful_ReviewId" ON "ReviewHelpful" ("ReviewId");

CREATE INDEX "IX_ReviewHelpful_UserId" ON "ReviewHelpful" ("UserId");

CREATE INDEX "IX_ReviewReplies_RetailerId" ON "ReviewReplies" ("RetailerId");

CREATE UNIQUE INDEX "IX_ReviewReplies_ReviewId" ON "ReviewReplies" ("ReviewId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260706120000_addreviewTables', '10.0.9');

COMMIT;

START TRANSACTION;
ALTER TABLE orders ADD "DeliveryPersonName" text;

ALTER TABLE orders ADD "DeliveryPersonPhone" text;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260707093836_deliverydetails', '10.0.9');

COMMIT;

START TRANSACTION;
CREATE TABLE "Coupons" (
    "CouponId" integer GENERATED BY DEFAULT AS IDENTITY,
    "CouponCode" character varying(30) NOT NULL,
    "Description" text NOT NULL,
    "DiscountType" integer NOT NULL,
    "DiscountValue" double precision NOT NULL,
    "MinimumOrderAmount" double precision NOT NULL,
    "MaximumDiscount" double precision,
    "StartDate" timestamp with time zone NOT NULL,
    "ExpiryDate" timestamp with time zone NOT NULL,
    "UsageLimit" integer,
    "UsedCount" integer NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedByUserId" integer NOT NULL,
    "CouponScope" integer NOT NULL,
    "RetailerId" integer,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Coupons" PRIMARY KEY ("CouponId"),
    CONSTRAINT "FK_Coupons_Retailers_RetailerId" FOREIGN KEY ("RetailerId") REFERENCES "Retailers" ("RetailerId")
);

CREATE UNIQUE INDEX "IX_Coupons_CouponCode" ON "Coupons" ("CouponCode");

CREATE INDEX "IX_Coupons_RetailerId" ON "Coupons" ("RetailerId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260709063133_coupon', '10.0.9');

COMMIT;

START TRANSACTION;
ALTER TABLE "Users" ADD "Status" text NOT NULL DEFAULT '';

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260709142417_newfieldinUserTable', '10.0.9');

COMMIT;

